Bootstrap: localimage
From: pylp_base/pylp_base:v1.3-dev.img

%help
This container contains micron microtubule tracking software.

%labels

Maintainer Nils Eckstein
Name micron

%setup
mkdir -p ${SINGULARITY_ROOTFS}/src/micron

%files
micron /src/micron/micron
requirements.txt /src/micron/requirements.txt
setup.py /src/micron/setup.py

%labels
maintainer ecksteinn@janelia.hhmi.org

%post

PATH="/miniconda/bin:$PATH"

pip install zarr

# install gunpowder

GUNPOWDER_ROOT=/src/gunpowder
GUNPOWDER_REPOSITORY=https://github.com/funkey/gunpowder.git
GUNPOWDER_REVISION=2ce2fdbee5c0bb5d2e12471e079a252f7fae54ea

mkdir -p ${GUNPOWDER_ROOT}
cd ${GUNPOWDER_ROOT}
git clone ${GUNPOWDER_REPOSITORY} . && \
git checkout ${GUNPOWDER_REVISION}
pip install -r requirements.txt
PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH

# install micron dependencies

DAISY_ROOT=/src/daisy
DAISY_REPOSITORY=https://github.com/funkey/daisy
DAISY_REVISION=3d7826e7e4ab5844d55debac9bbb00b4e43a998b

mkdir -p ${DAISY_ROOT}
cd ${DAISY_ROOT}
git clone ${DAISY_REPOSITORY} . && \
git checkout ${DAISY_REVISION}
pip install -r requirements.txt
pip install .

COMATCH_ROOT=/src/comatch
COMATCH_REPOSITORY=https://github.com/funkey/comatch
# Hungarian branch:
COMATCH_REVISION=dc0ca77e93bd48ef30dbfe63a444b50a684928dd

mkdir -p ${COMATCH_ROOT}
cd ${COMATCH_ROOT}
git clone ${COMATCH_REPOSITORY} . && \
git checkout ${COMATCH_REVISION}
python setup.py install

#install funlib.tensorflow.learn

FUNLIB_LEARN_TF_ROOT=/src/funlib.learn.tensorflow
FUNLIB_LEARN_TF_REPOSITORY=https://github.com/funkelab/funlib.learn.tensorflow.git
FUNLIB_LEARN_TF_REVISION=bb08e4ee3bab498d80dfdfee9e8f7fd6fd8975a0

mkdir -p ${FUNLIB_LEARN_TF_ROOT}
cd ${FUNLIB_LEARN_TF_ROOT}
git clone ${FUNLIB_LEARN_TF_REPOSITORY} . && \
git checkout ${FUNLIB_LEARN_TF_REVISION}
pip install -r requirements.txt
PYTHONPATH=${FUNLIB_LEARN_TF_ROOT}:$PYTHONPATH

# install micron
cd /src/micron
python setup.py build_ext --inplace
PYTHONPATH=/src/micron:$PYTHONPATH

#install funlib.run

FUNLIB_RUN_ROOT=/src/funlib.run
FUNLIB_RUN_REPOSITORY=https://github.com/funkelab/funlib.run.git
FUNLIB_RUN_REVISION=8e1501e8a44dd7cf7ed7f2f534a09c87a2562953

mkdir -p ${FUNLIB_RUN_ROOT}
cd ${FUNLIB_RUN_ROOT}
git clone ${FUNLIB_RUN_REPOSITORY} . && \
git checkout ${FUNLIB_RUN_REVISION}
pip install -r requirements.txt
PYTHONPATH=${FUNLIB_RUN_ROOT}:$PYTHONPATH

FUNLIB_MATH_ROOT=/src/funlib/math
FUNLIB_MATH_REPOSITORY=https://github.com/funkelab/funlib.math.git
FUNLIB_MATH_REVISION=80c841555050ed7b044c938c640f429599cbee70

mkdir -p ${FUNLIB_MATH_ROOT}
cd ${FUNLIB_MATH_ROOT}
git clone ${FUNLIB_MATH_REPOSITORY} . && \
git checkout ${FUNLIB_MATH_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${FUNLIB_MATH_ROOT}:$PYTHONPATH

FUNLIB_SEG_ROOT=/src/funlib/seg
FUNLIB_SEG_REPOSITORY=https://github.com/funkelab/funlib.segment
FUNLIB_SEG_REVISION=09246e7aed32210747800906846d03788ca10b81

mkdir -p ${FUNLIB_SEG_ROOT}
cd ${FUNLIB_SEG_ROOT}
git clone ${FUNLIB_SEG_REPOSITORY} . && \
git checkout ${FUNLIB_SEG_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${FUNLIB_SEG_ROOT}:$PYTHONPATH

LSD_ROOT=/src/lsd
LSD_REPOSITORY=https://github.com/funkelab/lsd.git
LSD_REVISION=8bd60cb8e50f70c706f5fa4dc6dcd5729e407a52

mkdir -p ${LSD_ROOT}
cd ${LSD_ROOT}
git clone ${LSD_REPOSITORY} . && \
git checkout ${LSD_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${LSD_ROOT}:$PYTHONPATH

pip install mahotas
pip install pymongo

%environment
export DAISY_ROOT=/src/daisy
export PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH
export GUNPOWDER_ROOT=/src/gunpowder
export PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH
export FUNLIB_LEARN_TF_ROOT=/src/funlib.learn.tensorflow
export PYTHONPATH=${FUNLIB_LEARN_TF_ROOT}:$PYTHONPATH
export PYTHONPATH=${FUNLIB_MATH_ROOT}:$PYTHONPATH
export PYTHONPATH=${LSD_ROOT}:$PYTHONPATH
export PYTHONPATH=${FUNLIB_SEG_ROOT}:$PYTHONPATH
export PYTHONPATH=/src/micron:$PYTHONPATH
export PYTHONPATH=${COMATCH_ROOT}:$PYTHONPATH
# ignore locally installed python modules (in ~/.local)
export PYTHONNOUSERSITE=True
# prevent multithreading in numpy
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

%runscript
exec /bin/bash "$@"
